Feature 23 new graph library
Metatavu/metamind-management pull request #24
Opened 2019-05-29 12:10 UTC by platonovsimeon

resolves #23

2019-06-04 06:00 UTC, anttileppa requested changes

2019-06-04 06:00 UTC, anttileppa commented on src/components/index/Graph.tsx
> +  public GraphViewRef: any;
this should be lowercased, moved into top of the class and marked as private

2019-06-04 06:00 UTC, anttileppa commented on src/components/index/Graph.tsx
> + // Handles node search
Change to proper tsdoc format

2019-06-04 06:00 UTC, anttileppa commented on src/components/index/Graph.tsx
> + private searchKnots = (): string[] => {
Fix indent (this and all following)

2019-06-04 06:00 UTC, anttileppa commented on src/components/index/GraphView.tsx
> +
Remove empty line

2019-06-04 06:00 UTC, anttileppa commented on src/actions/index.tsx
> +export interface ISetKnotPositions {
There should be empty line between two interfaces

2019-06-04 06:00 UTC, anttileppa commented on src/components/index/GraphView.tsx
> +export interface INode {
Empty line

2019-06-04 06:00 UTC, anttileppa commented on src/components/index/GraphView.tsx
> +export interface IEdge {
There should be an empty line between interfaces

2019-06-04 06:00 UTC, anttileppa commented on src/components/index/GraphView.tsx
> +  // Get called when props change
Proper tsdoc (change all)

2019-06-04 06:00 UTC, anttileppa commented on src/components/index/GraphView.tsx
> +
Remove empty line

2019-06-04 06:00 UTC, anttileppa commented on src/components/index/IntentEditor.tsx
> +            value={ this.state.intent.name }
Indent attributes with two spaces

2019-06-04 06:00 UTC, anttileppa commented on src/components/index/IntentEditor.tsx
> +
Remove empty line

2019-06-05 05:42 UTC, platonovsimeon commented on src/components/index/Graph.tsx
> +  public static getDerivedStateFromProps = (props: IProps, state: IState) => {
done

2019-06-05 05:42 UTC, platonovsimeon commented on src/components/index/Graph.tsx
> +  private static translateKnot(knot: Knot, x: number, y: number): INode {
done

2019-06-05 05:42 UTC, platonovsimeon commented on src/components/index/Graph.tsx
> +  private static translateIntent(intent: Intent, sourceNode: INode, targetNode: INode): IEdge {
done

2019-06-05 05:53 UTC, platonovsimeon commented on src/components/index/IntentEditor.tsx
> +
Empty line removed

2019-06-05 05:54 UTC, platonovsimeon commented on src/components/index/GraphView.tsx
> +
Empty line removed

2019-06-05 05:55 UTC, platonovsimeon commented on src/components/index/GraphView.tsx
> +export interface IEdge {
Added empty lines.

2019-06-05 05:57 UTC, platonovsimeon commented on src/components/index/GraphView.tsx
> +export interface INode {
Empty line added

2019-06-05 05:58 UTC, platonovsimeon commented on src/actions/index.tsx
> +export interface ISetKnotPositions {
Added an empty line

2019-06-05 08:15 UTC, platonovsimeon commented on src/components/index/IntentEditor.tsx
> +            value={ this.state.intent.name }
Indents added

2019-06-05 08:35 UTC, platonovsimeon commented on src/components/index/GraphView.tsx
> +  // Get called when props change
Formatted to tsdoc

2019-06-05 08:36 UTC, platonovsimeon commented on src/components/index/Graph.tsx
> +  public GraphViewRef: any;
graphViewRef is not being used

2019-06-05 08:37 UTC, platonovsimeon commented on src/components/index/Graph.tsx
> + // Handles node search
changed to tsdoc

2019-06-05 08:46 UTC, platonovsimeon commented on src/components/index/GraphView.tsx
> +
Removed

2019-06-05 08:59 UTC, platonovsimeon commented on src/components/index/Graph.tsx
> + private searchKnots = (): string[] => {
fixed

2019-06-05 09:03 UTC, platonovsimeon commented on src/components/index/Graph.tsx
> +  public GraphViewRef: any;
solved

2019-06-05 09:03 UTC, platonovsimeon commented on src/components/index/Graph.tsx
> + // Handles node search
solved

2019-06-05 09:03 UTC, platonovsimeon commented on src/components/index/Graph.tsx
> + private searchKnots = (): string[] => {
solved

2019-06-05 09:03 UTC, platonovsimeon commented on src/components/index/GraphView.tsx
> +  // Get called when props change
solved

2019-06-05 09:03 UTC, platonovsimeon commented on src/components/index/IntentEditor.tsx
> +            value={ this.state.intent.name }
solved

2019-06-05 09:04 UTC, platonovsimeon commented on src/components/index/GraphView.tsx
> +
solved

2019-06-05 18:24 UTC, merged