Feature 74 create story
Metatavu/metamind-management pull request #75
Opened 2021-06-22 09:29 UTC by veikkahonkanen

Resolves #74

2021-06-29 11:07 UTC, Chi-Chu319 commented on src/components/screens/home/home-screen.styles.ts
> +    borderRadius: "5px",
```suggestion
    borderRadius: 5,
```

2021-06-29 11:13 UTC, Chi-Chu319 reviewed
LGTM

2021-07-09 10:06 UTC, anttileppa requested changes

2021-07-09 10:06 UTC, anttileppa commented on src/components/screens/home/home-screen.tsx
> +    // TODO: implement importing of story from the .xml file
What is a story import XML file?

2021-07-09 10:06 UTC, anttileppa commented on src/components/screens/home/home-screen.tsx
> +  viewIndex: number;
viewIndex sounds a bit volatile, could you explain why this is an index based and not e.g. enumeration?

2021-07-09 10:06 UTC, anttileppa commented on src/components/screens/home/home-screen.tsx
> +  onReturnButtonClick = () => {
add modifier

2021-07-09 10:06 UTC, anttileppa commented on src/components/screens/home/home-screen.tsx
> +  onStoryNameChange = (event: React.ChangeEvent<HTMLInputElement>) => {
add modifier

2021-07-09 10:06 UTC, anttileppa commented on src/components/screens/home/home-screen.tsx
> +    this.setState({ newStoryName: value });
```suggestion

    this.setState({ 
      newStoryName: value
    });
```

2021-07-09 10:06 UTC, anttileppa commented on src/components/screens/home/home-screen.tsx
> +  onFilesDropped = (files: File[]) => {
add modifier

2021-07-09 10:06 UTC, anttileppa commented on src/components/screens/home/home-screen.tsx
> +      this.props.history.push(`editor/${createdStory.id}`);
```suggestion

      this.props.history.push(`editor/${createdStory.id}`);
```

2021-07-09 10:06 UTC, anttileppa commented on src/components/screens/home/home-screen.tsx
> +    this.setState({ newStoryName: value });
```suggestion

    this.setState({ newStoryName: value });
```

2021-07-09 10:06 UTC, anttileppa commented on src/components/screens/home/home-screen.tsx
> +    this.setState({ storyFile: files[0] });
```suggestion
    this.setState({ 
      storyFile: files[0] 
    });
```

2021-07-09 11:23 UTC, merged