Save button functionality, entities select lock, backspace deletion prevention to current fields
Metatavu/metamind-management pull request #79
Opened 2021-06-23 09:33 UTC by veikkahonkanen

2021-06-28 12:04 UTC, veikkahonkanen commented on src/localization/en.json
> +    "ok": "OK",
Do not use uppercase
```suggestion
    "ok": "Ok",
```

2021-06-29 11:03 UTC, Chi-Chu319 reviewed
LGTM

2021-07-09 13:16 UTC, anttileppa requested changes

2021-07-09 13:16 UTC, anttileppa commented on src/components/screens/editor/editor-screen.tsx
> +    try {
```suggestion

    try {
```

2021-07-09 13:16 UTC, anttileppa commented on src/components/screens/editor/editor-screen.tsx
> +      let currentKnots = knots ? knots : [];
This might be quite slow on larged stories, all update operations should be done within same Promise.all to ensure they are executed asynchronously

2021-07-09 13:16 UTC, anttileppa commented on src/components/screens/editor/editor-screen.tsx
> +    console.error(error);
Add proper error handling

2021-07-15 11:21 UTC, anttileppa approved these changes

2021-07-15 12:41 UTC, anttileppa requested changes

2021-07-15 12:41 UTC, anttileppa commented on src/components/screens/editor/editor-screen.tsx
> +  const onSaveClick = () => {
Change to async and use awaits in the code

2021-07-15 18:14 UTC, anttileppa requested changes

2021-07-15 18:14 UTC, anttileppa commented on src/components/screens/editor/editor-screen.tsx
> +
Hi, I meant something like this with my previous comment:

```suggestion
      const knotsApi = Api.getKnotsApi(accessToken);
      const intentsApi = Api.getIntentsApi(accessToken);
      const trainingMaterialsApi = Api.getTrainingMaterialApi(accessToken);
      const storyApi = Api.getStoriesApi(accessToken);

      const storyPromise = story? storyApi.updateStory({ storyId: storyId, story: story }) : undefined;
      
      const knotUpdatePromises = (knots || []).map(knot => (
        knot.id? knotsApi.updateKnot({
          storyId: storyId,
          knotId: knot.id,
          knot: knot
        }) : knotsApi.createKnot({
          storyId: storyId,
          knot: knot
        })
      ));

      const knotDeletePromises = removedKnots.map(knot => (
        knotsApi.deleteKnot({
          storyId: storyId,
          knotId: knot.id!!
        })
      ));
      
      const intentUpdatePromises = (intents || []).map(intent => (
        intent.id? intentsApi.updateIntent({
          storyId: storyId,
          intentId: intent.id,
          intent: intent
        }) : intentsApi.createIntent({
          storyId: storyId,
          intent: intent
        })
      ));

      const intentDeletePromises = removedIntents.map(intent => (
        intentsApi.deleteIntent({
          storyId: storyId,
          intentId: intent.id!!
        })
      ));

      const trainingMaterialUpdatePromises = (trainingMaterial || []).map(material => (
        material.id? trainingMaterialsApi.updateTrainingMaterial({
          trainingMaterialId: material.id,
          trainingMaterial: material
        }) : trainingMaterialsApi.createTrainingMaterial({
          trainingMaterial: material
        })
      ));

      const [ updatedStory, updatedKnots, updatedIntents, updatedMaterials, knotDeletePromises, intentDeletePromises ] = await Promise.all([ 
        storyPromise, 
        Promise.all(knotUpdatePromises), 
        Promise.all(intentUpdatePromises), 
        Promise.all(trainingMaterialUpdatePromises)
      ])

      setStoryData({
        story: updatedStory,
        knots: updatedKnots,
        intents: updatedIntents,
        trainingMaterial: updatedMaterials
      });

      setRemovedKnots([]);
      setRemovedIntents([]);
```

2021-07-19 07:04 UTC, anttileppa requested changes

2021-07-19 07:04 UTC, anttileppa commented on src/components/knot-components/discussion-component/discussion-component.tsx
> +  classes: any,
any?

2021-07-19 07:04 UTC, anttileppa commented on src/components/knot-components/discussion-component/discussion-component.tsx
> +
```suggestion
```

2021-07-19 07:04 UTC, anttileppa commented on src/components/knot-components/discussion-component/discussion-component.tsx
> +  classes: any,
any?

2021-07-19 07:04 UTC, anttileppa commented on src/components/screens/editor/editor-screen.tsx
> +      const storyPromise = story? storyApi.updateStory({ storyId: storyId, story: story }) : undefined;
```suggestion
      const storyPromise = story ? storyApi.updateStory({ storyId: storyId, story: story }) : undefined;
```

2021-07-19 07:04 UTC, anttileppa commented on src/components/screens/editor/editor-screen.tsx
> +      ])
Instead of callbacks, use separate awaits

2021-07-19 07:33 UTC, anttileppa approved these changes

2021-07-19 07:33 UTC, merged