Delete from list funtionalities
Metatavu/metamind-management pull request #84
Opened 2021-06-24 04:38 UTC by veikkahonkanen

Resolves #82

2021-06-29 10:45 UTC, Chi-Chu319 commented on src/components/knot-components/knot-list/knot-list.tsx
> +              }
```suggestion
              return KnotScope.Home? {
                  <InteractiveListItem
                    icon={ <HomeIcon htmlColor="#000"/> }
                    title={ knot.name }
                    onClick={ () => onKnotClick(knot) }
                  />
                } : {
                  <InteractiveListItem
                    icon={ <KnotIcon htmlColor="#000"/> }
                    title={ knot.name }
                    onClick={ () => onKnotClick(knot) }
                    onSecondaryActionClick={ () => onKnotSecondaryClick(knot) }
                    secondaryActionIcon={ <DeleteOutlineIcon htmlColor="#000"/> }
                  />
                }
```

2021-06-29 10:49 UTC, Chi-Chu319 commented on src/components/views/story-editor-view/story-editor-view.tsx
> +      console.log(node)
```suggestion
```

2021-06-29 10:50 UTC, Chi-Chu319 commented on src/components/views/story-editor-view/story-editor-view.tsx
> +      console.log(link)
```suggestion
```

2021-06-29 10:51 UTC, Chi-Chu319 requested changes
Changes requested

2021-07-27 11:14 UTC, lauriLukkarinen approved these changes

2021-07-27 11:14 UTC, lauriLukkarinen commented on src/components/generic/generic-dialog/generic-dialog.tsx
> +const GenericDialog: React.FC<Props> = ({
```suggestion
/**
 * React component displaying confirm dialogs
 *
 * @param props component properties
 */
const GenericDialog: React.FC<Props> = ({
```

2021-07-27 11:14 UTC, lauriLukkarinen commented on src/components/generic/list-items/interactive-list-item.tsx
> +      { (onSecondaryActionClick && secondaryActionIcon) &&
```suggestion
      { onSecondaryActionClick && secondaryActionIcon &&
```

2021-07-27 11:14 UTC, lauriLukkarinen commented on src/components/knot-components/knot-list/knot-list.tsx
> +            })
```suggestion
            knots.map(knot =>
              <InteractiveListItem
                icon={ <KnotIcon htmlColor="#000"/> }
                title={ knot.name }
                onClick={ () => onKnotClick(knot) }
                onSecondaryActionClick={
                  knot.scope === KnotScope.Home ?
                    () => onKnotSecondaryClick(knot) :
                    undefined
                }
                secondaryActionIcon={
                  knot.scope === KnotScope.Home ?
                    <DeleteOutlineIcon htmlColor="#000"/> :
                    undefined
                }
              />
            )
```

2021-07-27 11:14 UTC, lauriLukkarinen commented on src/components/screens/editor/editor-screen.tsx
> +  }
```suggestion
  const onDeleteFromListClick = (entity: Knot | Intent) => {
    setStoryData({
      ...storyData,
      selectedIntent: (entity as Intent).sourceKnotId ?
        entity as Intent :
        entity as Knot,
      selectedKnot: undefined
    });

    setDeleteConfirmDialogOpen(true);
  }
```

2021-07-27 11:14 UTC, lauriLukkarinen commented on src/components/screens/editor/editor-screen.tsx
> +        error= { false }
```suggestion
        open={ deleteConfirmDialogOpen }
        error={ false }
```

2021-08-09 06:06 UTC, merged