Knot search & intent search functionality
Metatavu/metamind-management pull request #88
Opened 2021-06-29 07:37 UTC by veikkahonkanen

Resolves #87

2021-06-29 09:49 UTC, Chi-Chu319 commented on src/components/intent-components/intent-list/intent-list.tsx
> +  }
maybe better to use ternary expression
```suggestion
    { intents? <List>
        {
          intents.filter(item => item.name?.toLowerCase().includes(searchValue.toLowerCase())).map(intent => (
            <InteractiveListItem
              icon={ <IntentIcon/> }
              title={ intent.name ?? "" }
              onClick={ () => onIntentClick(intent) }
            />
          ))
        }
      </List> : null
    }
```

2021-06-29 09:56 UTC, Chi-Chu319 commented on src/components/knot-components/knot-list/knot-list.tsx
> +    );
```suggestion
    return knots? { 
      <List>
        {
          knots.filter(item => item.name.toLowerCase().includes(searchValue.toLowerCase())).map(knot => (
            <InteractiveListItem
              icon={ <KnotIcon htmlColor="#000"/> }
              title={ knot.name }
              onClick={ () => onKnotClick(knot) }
            />
          ))
        }
      </List>
    } : null
```

2021-06-29 10:00 UTC, Chi-Chu319 requested changes
Changes requested

2021-07-27 11:22 UTC, lauriLukkarinen approved these changes

2021-07-27 11:22 UTC, lauriLukkarinen commented on src/components/intent-components/intent-list/intent-list.tsx
> +    ) : null;
```suggestion
    if (!intents) {
      return null;
    }

    return (
      <List>
        { intents
          .filter(item => item.name?.toLowerCase().includes(searchValue.toLowerCase()))
          .map(intent =>
            <InteractiveListItem
              icon={ <IntentIcon/> }
              title={ intent.name ?? "" }
              onClick={ () => onIntentClick(intent) }
            />
          )
        }
      </List>
    );
```

2021-07-27 11:22 UTC, lauriLukkarinen commented on src/components/intent-components/intent-list/intent-list.tsx
> +      </>
```suggestion
        <>
          <AccordionItem title={ strings.editorScreen.intents.normalIntents }>
            { renderIntentGroups(IntentType.NORMAL) }
          </AccordionItem>
          <AccordionItem title={ strings.editorScreen.intents.defaultIntents }>
            { renderIntentGroups(IntentType.DEFAULT) }
          </AccordionItem>
          <AccordionItem title={ strings.editorScreen.intents.confusedIntents }>
            { renderIntentGroups(IntentType.CONFUSED) }
          </AccordionItem>
          <AccordionItem title={ strings.editorScreen.intents.redirectIntents }>
            { renderIntentGroups(IntentType.REDIRECT) }
          </AccordionItem>
        </>
```

2021-07-27 11:22 UTC, lauriLukkarinen commented on src/components/knot-components/knot-list/knot-list.tsx
> +  }
```suggestion
  const renderSearchedKnots = () => {
    if (!knots) {
      return null;
    }

    return (
      <List>
        { knots
          .filter(item => item.name.toLowerCase().includes(searchValue.toLowerCase()))
          .map(knot =>
            <InteractiveListItem
              icon={ <KnotIcon htmlColor="#000"/> }
              title={ knot.name }
              onClick={ () => onKnotClick(knot) }
            />
          )
        }
      </List>
    );
  }
```

2021-08-09 06:14 UTC, merged