Feature 83 connect to bot
Metatavu/metamind-management pull request #99
Opened 2021-07-01 12:38 UTC by Chi-Chu319

Message components from metamind bot

2021-07-15 13:01 UTC, Chi-Chu319 commented
loading component for saveing

2021-07-27 13:01 UTC, lauriLukkarinen requested changes

2021-07-27 13:01 UTC, lauriLukkarinen commented on src/components/generic/loading-item/loading-item.tsx
> +}) => {
```suggestion
/**
 * Loading item component
 *
 * @param props component properties
 */
const Loading: React.FC<Props> = ({ text }) => {
```

2021-07-27 13:01 UTC, lauriLukkarinen commented on src/components/layouts/app-layout/app-layout.tsx
> +            <NavLink exact to={ `/editor/${storyData.story?.id}` } style={{ textDecoration: "none" }}>
```suggestion
            <NavLink
              exact
              to={ `/editor/${storyData.story?.id}` }
              style={{ textDecoration: "none" }}
            >
```

2021-07-27 13:01 UTC, lauriLukkarinen commented on src/components/layouts/app-layout/app-layout.tsx
> +            <NavLink exact to={ `/preview/${storyData.story?.id}` } style={{ textDecoration: "none" }}>
```suggestion
            <NavLink
              exact
              to={ `/preview/${storyData.story?.id}` }
              style={{ textDecoration: "none" }}
            >
```

2021-07-27 13:01 UTC, lauriLukkarinen commented on src/components/screens/editor/editor-screen.tsx
> +    if (!storyLoading && storyData && storyData.story?.id === storyId){
```suggestion
    if (!storyLoading && storyData?.story?.id === storyId) {
```

2021-07-27 13:01 UTC, lauriLukkarinen commented on src/components/screens/editor/editor-screen.tsx
> +      <Box style={{ height: "100%", width: "100%", alignItems: "center", justifyContent: "center", display: "flex" }}>
Move inline styles to style file

2021-07-27 13:01 UTC, lauriLukkarinen commented on src/components/screens/editor/editor-screen.tsx
> +  const { story, knots, selectedKnot, selectedIntent, intents, trainingMaterial, scripts } = storyData;
```suggestion
  const {
    story,
    knots,
    selectedKnot,
    selectedIntent,
    intents,
    trainingMaterial,
    scripts
  } = storyData;
```

2021-07-27 13:01 UTC, lauriLukkarinen commented on src/components/screens/preview/preview-screen.styles.ts
> +}, {
```suggestion
export const usePreviewStyles = makeStyles({

  previewContainer: {
    // 100% height substracted with two toolbars and extra spacing for tight fit
    height: `calc(100% - ${toolbarHeight}px - ${theme.spacing(2)}px)`,
    width: "50%",
    display: "flex",
    margin: "auto"
  }

}, {
```

2021-07-27 13:01 UTC, lauriLukkarinen commented on src/components/screens/preview/preview-screen.tsx
>   */
```suggestion
/**
 * Preview screen component
 *
 * @param props component properties
 */
```

2021-07-27 13:01 UTC, lauriLukkarinen commented on src/components/screens/preview/preview-screen.tsx
> +    setConversationStarted((conversationStarted) => true)
```suggestion
    setConversationStarted(true);
```

2021-07-27 13:01 UTC, lauriLukkarinen commented on src/components/screens/preview/preview-screen.tsx
> +   * Bot reset
```suggestion
   * Bot reset
```

2021-07-27 13:01 UTC, lauriLukkarinen commented on src/components/screens/preview/preview-screen.tsx
> +    setConversationStarted((conversationStarted) => false);
```suggestion
    setMessageDatas([]);
    setConversationStarted(false);
```

2021-07-27 13:01 UTC, lauriLukkarinen commented on src/components/screens/preview/preview-screen.tsx
> +    ])
```suggestion
    ]);
```

2021-07-27 13:01 UTC, lauriLukkarinen commented on src/components/screens/preview/preview-screen.tsx
> +    )
```suggestion
    );
```

2021-07-27 13:01 UTC, lauriLukkarinen commented on src/components/screens/preview/preview-screen.tsx
> +      setMessagesEnd((messageEndPrev) => messagesEnd);
```suggestion
      setMessagesEnd(messagesEnd);
```

2021-07-27 13:01 UTC, lauriLukkarinen commented on src/components/screens/preview/preview-screen.tsx
> +    const messagesEndUpdate = (messagesEnd?: HTMLDivElement) => {
```suggestion
  /**
   * Update the message end
   *
   * @param messagesEnd message end
   */
    const messagesEndUpdate = (messagesEnd?: HTMLDivElement) => {
```

2021-07-27 13:01 UTC, lauriLukkarinen commented on src/components/screens/preview/preview-screen.tsx
> +    if (!storyLoading && storyData && storyData.story?.id === storyId){
```suggestion
    if (!storyLoading && storyData?.story?.id === storyId) {
```

2021-07-27 13:01 UTC, lauriLukkarinen commented on src/components/screens/preview/preview-screen.tsx
> +      <Box style={{ height: "100%", width: "100%", alignItems: "center", justifyContent: "center", display: "flex" }}>
Move inline styles to style file

2021-07-27 13:01 UTC, lauriLukkarinen commented on src/components/screens/preview/preview-screen.tsx
> +  const [ messagesEnd, setMessagesEnd ] = React.useState<HTMLDivElement | undefined>(undefined);
```suggestion
  const [ messagesEnd, setMessagesEnd ] = React.useState<HTMLDivElement>();
```

2021-07-27 13:01 UTC, lauriLukkarinen commented on src/components/screens/preview/preview-screen.tsx
> +        <Box height="49px" display="flex" borderBottom={1}>
```suggestion
        <Box height="49px" display="flex" borderBottom={ 1 }>
```

2021-07-27 13:01 UTC, lauriLukkarinen commented on src/components/screens/preview/preview-screen.tsx
> +  const renderPreviewContent = () => {
```suggestion
  /**
   * Renders preview content
   */
  const renderPreviewContent = () => {
```

2021-07-27 13:01 UTC, lauriLukkarinen commented on src/components/screens/preview/preview-screen.tsx
> +    }
```suggestion
    }

```

2021-07-27 13:01 UTC, lauriLukkarinen commented on src/components/screens/preview/preview-screen.tsx
> +  const { story, knots, selectedKnot, selectedIntent, intents, trainingMaterial } = storyData;
```suggestion
  const {
    story,
    knots,
    selectedKnot,
    selectedIntent,
    intents,
    trainingMaterial
  } = storyData;
```

2021-07-27 13:01 UTC, lauriLukkarinen commented on src/components/views/story-preview-view/story-preview-view.tsx
> +    if (messageDatas.length !== 0) {
```suggestion
    if (messageDatas.length) {
```

2021-07-27 13:01 UTC, lauriLukkarinen commented on src/localization/strings.ts
> +  previewScreen: {
```suggestion
  /**
   * Translations related to preview screen
   */
  previewScreen: {
```

2021-07-27 13:01 UTC, lauriLukkarinen commented on src/reducers/story.ts
> +
```suggestion
```

2021-07-27 13:01 UTC, lauriLukkarinen commented on src/reducers/story.ts
> +      };
```suggestion
      return { 
        ...state,
        storyData: action.storyData,
        storyLoading: false 
      };
```

2021-07-29 06:59 UTC, lauriLukkarinen approved these changes

2021-07-29 06:59 UTC, lauriLukkarinen commented on src/components/screens/editor/editor-screen.tsx
> +    </AppLayout>
```suggestion
      <AppLayout
        keycloak={ keycloak }
        pageTitle={ strings.loading.loading }
      >
        { renderLoading() }
      </AppLayout>
```

2021-07-29 06:59 UTC, lauriLukkarinen commented on src/components/screens/preview/preview-screen.tsx
> +import { StoryData } from "../../../types"
```suggestion
import { StoryData } from "../../../types";
```

2021-07-29 06:59 UTC, lauriLukkarinen commented on src/components/screens/preview/preview-screen.tsx
> +    setMessageDatas((messageDatas) =>
```suggestion
    setMessageDatas(messageDatas =>
```

2021-07-29 06:59 UTC, lauriLukkarinen commented on src/components/screens/preview/preview-screen.tsx
> +    setMessageDatas((messageDatas) => [
```suggestion
    setMessageDatas(messageDatas => [
```

2021-07-29 06:59 UTC, lauriLukkarinen commented on src/components/screens/preview/preview-screen.tsx
> +  const { story,
```suggestion
  const {
    story,
```

2021-07-29 06:59 UTC, lauriLukkarinen commented on src/components/views/story-preview-view/story-preview-view.tsx
> +import MessageInput from "metamind-metatavu-bot/dist/components/message-input/message-input"
```suggestion
import MessageList from "metamind-metatavu-bot/dist/components/message-list/message-list";
import MessageInput from "metamind-metatavu-bot/dist/components/message-input/message-input";
```

2021-07-29 07:02 UTC, merged